@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri May 14 17:36:20 +0300 2021
REM SW Build 3118627 on Tue Feb  9 05:14:06 MST 2021
REM
REM Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 1e56a5d2cb5c48bba3f864c7297a8e35 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Clock_Generator_behav xil_defaultlib.Clock_Generator -log elaborate.log"
call xelab  -wto 1e56a5d2cb5c48bba3f864c7297a8e35 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Clock_Generator_behav xil_defaultlib.Clock_Generator -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
