webtalk_init -webtalk_dir D:/VHDL Vivado Codes/VHDL-Working-Place/8bitcounter/8bitcounter.sim/sim_1/behav/xsim/xsim.dir/eightbitcounter_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 12 11:33:20 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3118627" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f072e2a0-4f3a-4711-bfb5-0709159052d9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "50d033bea4214c66b9d39c0987b87810" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3410 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "411963800 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14384_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3537949943 -regid "" -xml D:/VHDL Vivado Codes/VHDL-Working-Place/8bitcounter/8bitcounter.sim/sim_1/behav/xsim/xsim.dir/eightbitcounter_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/VHDL Vivado Codes/VHDL-Working-Place/8bitcounter/8bitcounter.sim/sim_1/behav/xsim/xsim.dir/eightbitcounter_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/VHDL Vivado Codes/VHDL-Working-Place/8bitcounter/8bitcounter.sim/sim_1/behav/xsim/xsim.dir/eightbitcounter_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
